package category

type Category string

const (
	AndroidWear       Category = "ANDROID_WEAR"
	ArtAndDesign      Category = "ART_AND_DESIGN"
	AutoAndVehicles   Category = "AUTO_AND_VEHICLES"
	Beauty            Category = "BEAUTY"
	BooksAndReference Category = "BOOKS_AND_REFERENCE"
	Business          Category = "BUSINESS"
	Comics            Category = "COMICS"
	Communication     Category = "COMMUNICATION"
	Dating            Category = "DATING"
	Education         Category = "EDUCATION"
	Entertainment     Category = "ENTERTAINMENT"
	Events            Category = "EVENTS"
	Family            Category = "FAMILY"
	FamilyAction      Category = "FAMILY_ACTION"
	FamilyBraingames  Category = "FAMILY_BRAINGAMES"
	FamilyCreate      Category = "FAMILY_CREATE"
	FamilyEducation   Category = "FAMILY_EDUCATION"
	FamilyMusicvideo  Category = "FAMILY_MUSICVIDEO"
	FamilyPretend     Category = "FAMILY_PRETEND"
	Finance           Category = "FINANCE"
	FoodAndDrink      Category = "FOOD_AND_DRINK"
	Game              Category = "GAME"
	GameAction        Category = "GAME_ACTION"
	GameAdventure     Category = "GAME_ADVENTURE"
	GameArcade        Category = "GAME_ARCADE"
	GameBoard         Category = "GAME_BOARD"
	GameCard          Category = "GAME_CARD"
	GameCasino        Category = "GAME_CASINO"
	GameCasual        Category = "GAME_CASUAL"
	GameEducational   Category = "GAME_EDUCATIONAL"
	GameMusic         Category = "GAME_MUSIC"
	GamePuzzle        Category = "GAME_PUZZLE"
	GameRacing        Category = "GAME_RACING"
	GameRolePlaying   Category = "GAME_ROLE_PLAYING"
	GameSimulation    Category = "GAME_SIMULATION"
	GameSports        Category = "GAME_SPORTS"
	GameStrategy      Category = "GAME_STRATEGY"
	GameTrivia        Category = "GAME_TRIVIA"
	GameWord          Category = "GAME_WORD"
	HealthAndFitness  Category = "HEALTH_AND_FITNESS"
	HouseAndHome      Category = "HOUSE_AND_HOME"
	LibrariesAndDemo  Category = "LIBRARIES_AND_DEMO"
	Lifestyle         Category = "LIFESTYLE"
	MapsAndNavigation Category = "MAPS_AND_NAVIGATION"
	Medical           Category = "MEDICAL"
	MusicAndAudio     Category = "MUSIC_AND_AUDIO"
	NewsAndMagazines  Category = "NEWS_AND_MAGAZINES"
	Parenting         Category = "PARENTING"
	Personalization   Category = "PERSONALIZATION"
	Photography       Category = "PHOTOGRAPHY"
	Productivity      Category = "PRODUCTIVITY"
	Shopping          Category = "SHOPPING"
	Social            Category = "SOCIAL"
	Sports            Category = "SPORTS"
	Tools             Category = "TOOLS"
	TravelAndLocal    Category = "TRAVEL_AND_LOCAL"
	VideoPlayers      Category = "VIDEO_PLAYERS"
	Weather           Category = "WEATHER"
)
